#!/usr/bin/env python3
"""Hermetic tests for the portability-audit infrastructure (stdlib only).

Runs entirely offline: no network, no installed ``polytoken`` binary.  The
only subprocesses spawned are the three CLI scripts themselves.  A fake
``polytoken vfs cat`` replacement (served through the test-only
``PORTABILITY_VFS_CAT_COMMAND``) makes replay hermetic.

The valid fixture is generated by the shared parser itself, so the recorded
evidence is guaranteed internally consistent; negatives then break one
category at a time.  Covers the exact negative categories from the plan:

* the shared parser: transclude-quoted ``polytoken://`` URIs plus literal
  ``polytoken://`` tokens, normalization, lexical ordering, and unsupported
  schemes that warn on stderr only and do **not** become dependencies
* the validator: the ten exact headings, the 12 exact capability IDs,
  the 23 exact semantic IDs, <=3 RECOMMENDATION markers each with the five
  fields, the exact eight evidence arrays (unknown keys rejected), the six
  exact roots with root ``parent_uri`` null only, closure/unresolved
  consistency, resource-field requirements, workflow_stages /
  case-study-citation / local-citation field semantics, the five manual-review
  IDs all passing, cited paths/URIs/URLs, and roadmap path/status
* replay: exact ``polytoken vfs cat <uri>`` invocation in deterministic URI
  order, raw stdout byte SHA-256 comparison, closure/unresolved recompute,
  offline URL syntax validation, and the test-only cat override
* parser-warning stdout/stderr parity between validator and replay, plus a
  no-warnings-on-valid-fixture guarantee
"""
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import portability_evidence_parser as parser       # noqa: E402
import validate_portability_audit as validator     # noqa: E402
import replay_portability_evidence as replay       # noqa: E402

AUDIT_NAME = "PORTABILITY.md"
EVIDENCE_NAME = "PORTABILITY.json"
ROADMAP_NAME = "ROADMAP.md"

VALID_ROADMAP_TEXT = (
    "# Roadmap\n\nPortability audit roadmap notes.\n\n"
    "## Landed\n\n- Portability audit infrastructure.\n"
)

FAKE_CAT = """import json, sys
catmap, log, uri = sys.argv[1], sys.argv[2], sys.argv[3]
with open(log, "a", encoding="utf-8") as fh:
    fh.write(uri + "\\n")
m = json.load(open(catmap, encoding="utf-8"))
if uri not in m:
    sys.exit(1)
sys.stdout.buffer.write(m[uri].encode("utf-8"))
"""

URL_REF = "https://docs.github.com/en/copilot/reference/hooks-reference"

# Capability -> semantic-ID assignment (single source of truth for the
# matrix and the evidence semantic_sources).
CAP_TO_SEM = {
    "RESEARCH_DECOMPOSITION": ["WEB_SEARCH"],
    "SUBAGENT_HANDOFF": ["SUBAGENT_INVOCATION", "SUBAGENT_RESULT_RETURN"],
    "EVIDENCE_CONTRACTS": ["SKILL_LOADING", "SESSION_CONTINUITY"],
    "FACET_SEPARATION": ["FACET_PROMPT_COMPOSITION", "FACET_TRANSITIONS",
                         "FACET_MODEL_SELECTION"],
    "MODEL_TOOL_SKILL_SCOPING": ["SUBAGENT_TOOL_INHERITANCE",
                                 "SUBAGENT_SKILL_ACCESS",
                                 "FACET_TOOL_FILTERING",
                                 "FACET_SKILL_FILTERING"],
    "PLAN_REVIEW_GATE": ["SUBAGENT_MODEL_CONFIG"],
    "ADVERSARIAL_REVIEW": ["SUBAGENT_ISOLATION"],
    "MECHANICAL_ENFORCEMENT": ["FACET_PERMISSION_HINT", "HOOK_TIMING",
                               "HOOK_ENFORCEMENT"],
    "CONTEXT_RESUME_STATE": ["FACET_COMPACTION_HINT"],
    "COMPLETION_SUMMARY": ["SESSION_COMPACTION", "SESSION_CLEAR"],
    "TEMPLATING_COMPOSABILITY": ["TEMPLATING_RUNTIME",
                                 "TRANSCLUDE_SEMANTICS"],
    "OBSERVABILITY": ["VFS_INSPECTION"],
}

# Semantic ID -> evidence uri (root) used in semantic_sources.
SEM_TO_URI = {
    "WEB_SEARCH": "polytoken://subagents/researcher.md",
    "SUBAGENT_INVOCATION": "polytoken://facets/orchestrate.md",
    "SUBAGENT_RESULT_RETURN": "polytoken://facets/orchestrate.md",
    "SKILL_LOADING": "polytoken://subagents/researcher.md",
    "SESSION_CONTINUITY": "polytoken://facets/plan.md",
    "FACET_PROMPT_COMPOSITION": "polytoken://facets/plan.md",
    "FACET_TRANSITIONS": "polytoken://facets/plan.md",
    "FACET_MODEL_SELECTION": "polytoken://facets/plan.md",
    "SUBAGENT_TOOL_INHERITANCE": "polytoken://subagents/general-purpose.md",
    "SUBAGENT_SKILL_ACCESS": "polytoken://subagents/researcher.md",
    "FACET_TOOL_FILTERING": "polytoken://facets/plan.md",
    "FACET_SKILL_FILTERING": "polytoken://facets/plan.md",
    "SUBAGENT_MODEL_CONFIG": "polytoken://subagents/plan-reviewer.md",
    "SUBAGENT_ISOLATION": "polytoken://facets/orchestrate.md",
    "FACET_PERMISSION_HINT": "polytoken://facets/plan.md",
    "HOOK_TIMING": "polytoken://facets/plan.md",
    "HOOK_ENFORCEMENT": "polytoken://facets/plan.md",
    "FACET_COMPACTION_HINT": "polytoken://facets/plan.md",
    "SESSION_COMPACTION": "polytoken://facets/orchestrate.md",
    "SESSION_CLEAR": "polytoken://facets/orchestrate.md",
    "TEMPLATING_RUNTIME": "polytoken://facets/plan.md",
    "TRANSCLUDE_SEMANTICS": "polytoken://facets/plan.md",
    "VFS_INSPECTION": "polytoken://facets/orchestrate.md",
}

VERDICTS = {
    "RESEARCH_DECOMPOSITION": "portable",
    "SUBAGENT_HANDOFF": "portable",
    "EVIDENCE_CONTRACTS": "partial",
    "FACET_SEPARATION": "gap",
    "MODEL_TOOL_SKILL_SCOPING": "partial",
    "PLAN_REVIEW_GATE": "portable",
    "ADVERSARIAL_REVIEW": "partial",
    "MECHANICAL_ENFORCEMENT": "gap",
    "CONTEXT_RESUME_STATE": "partial",
    "COMPLETION_SUMMARY": "portable",
    "TEMPLATING_COMPOSABILITY": "gap",
    "OBSERVABILITY": "partial",
}

# Retrieved content for the six roots.  The builder derives references,
# hashes, closure, and unresolved from this, so the fixture is always
# internally consistent no matter how a test mutates it.
DEFAULT_CONTENT = {
    "polytoken://facets/plan.md": (
        "You are in plan facet.\n"
        "{{ transclude(\"polytoken://system_prompts/facet.md\") }}\n"
        "{{ transclude(\"polytoken://resources/plan_spec_default.md\") }}\n"
    ),
    "polytoken://facets/execute.md": (
        "{{ transclude(\"polytoken://system_prompts/facet.md\") }}\n"
    ),
    "polytoken://facets/orchestrate.md": (
        "{{ transclude(\"polytoken://system_prompts/facet.md\") }}\n"
    ),
    "polytoken://subagents/researcher.md": (
        "Read-only researcher.\n"
    ),
    "polytoken://subagents/plan-reviewer.md": (
        "{{ transclude(\"polytoken://resources/plan_spec_default.md\") }}\n"
    ),
    "polytoken://subagents/general-purpose.md": (
        "General-purpose delegate.\n"
    ),
}

LOCAL_CITATIONS = [
    {"path": "AGENTS.md"},
    {"path": "ROADMAP.md"},
    {"path": "scripts/portability_evidence_parser.py"},
    {"path": "scripts/validate_portability_audit.py"},
    {"path": "scripts/replay_portability_evidence.py"},
]

CASE_STUDY_CITATIONS = [
    {"label": "research delegation failure / missing evidence controls",
     "uri": "polytoken://subagents/researcher.md", "status": "observed"},
    {"label": "AirPods portability case study",
     "uri": "polytoken://case-studies/airpods-portability.md",
     "status": "unresolved"},
]

WORKFLOW_STAGES = [
    {"stage": "Plan facet read-only planning",
     "source_uri": "polytoken://facets/plan.md",
     "semantic_ids": ["FACET_PROMPT_COMPOSITION", "FACET_MODEL_SELECTION",
                      "FACET_TOOL_FILTERING", "FACET_SKILL_FILTERING",
                      "FACET_PERMISSION_HINT", "HOOK_TIMING",
                      "HOOK_ENFORCEMENT", "FACET_COMPACTION_HINT",
                      "SESSION_CONTINUITY", "TEMPLATING_RUNTIME",
                      "TRANSCLUDE_SEMANTICS"]},
    {"stage": "Execute facet implementation",
     "source_uri": "polytoken://facets/execute.md",
     "semantic_ids": ["FACET_TRANSITIONS"]},
    {"stage": "Orchestrate facet delegation",
     "source_uri": "polytoken://facets/orchestrate.md",
     "semantic_ids": ["SUBAGENT_INVOCATION", "SUBAGENT_RESULT_RETURN",
                      "SUBAGENT_ISOLATION", "SESSION_COMPACTION",
                      "SESSION_CLEAR", "VFS_INSPECTION"]},
    {"stage": "Researcher evidence gathering",
     "source_uri": "polytoken://subagents/researcher.md",
     "semantic_ids": ["WEB_SEARCH", "SKILL_LOADING",
                      "SUBAGENT_SKILL_ACCESS"]},
    {"stage": "Plan-reviewer gate",
     "source_uri": "polytoken://subagents/plan-reviewer.md",
     "semantic_ids": ["SUBAGENT_MODEL_CONFIG"]},
    {"stage": "General-purpose inherit-tools delegate",
     "source_uri": "polytoken://subagents/general-purpose.md",
     "semantic_ids": ["SUBAGENT_TOOL_INHERITANCE"]},
]


# ---------------------------------------------------------------------------
# Fixture builder
# ---------------------------------------------------------------------------

def build_evidence(content):
    """Build a valid evidence object from a content map (via the parser)."""
    roots = list(parser.EXPECTED_ROOTS)
    resources = []
    for uri in roots:
        text = content[uri]
        resources.append({
            "uri": uri,
            "parent_uri": None,
            "retrieval_status": "retrieved",
            "content": text,
            "content_sha256": parser.hash_content(text),
            "discovered_references": parser.references_from_scan(
                parser.scan_content(text)),
        })
    closure, unresolved = parser.recompute_evidence(roots, resources)
    semantic_sources = [
        {"claim_id": sid, "capability": cap, "url": SEM_TO_URI[sid],
         "revision_or_version": "polytoken-local-2026-09-01",
         "retrieval_date": "2026-09-01",
         "supported_claim": "Captured source supports %s." % sid,
         "evidence_class": "observed"}
        for cap, sids in CAP_TO_SEM.items() for sid in sids
    ]
    manual = [{"id": mid, "status": "pass", "note": "verified by operator"}
              for mid in parser.MANUAL_REVIEW_IDS]
    return {
        "roots": roots,
        "resources": resources,
        "unresolved_references": unresolved,
        "semantic_sources": semantic_sources,
        "local_citations": [dict(r) for r in LOCAL_CITATIONS],
        "workflow_stages": [dict(r) for r in WORKFLOW_STAGES],
        "case_study_citations": [dict(r) for r in CASE_STUDY_CITATIONS],
        "manual_review": manual,
    }


def build_audit(evidence):
    """Build the canonical valid audit markdown from the evidence object."""
    roots = list(parser.EXPECTED_ROOTS)
    lines = [
        "# Portability Audit",
        "",
        "## Executive answer",
        "Polytoken facets/subagents port to Copilot CLI with partial "
        "fidelity; see matrix.",
        "",
        "## Scope, assumptions, and evidence quality",
        "Grounded in the six captured facet/subagent roots.",
        "Evidence: " + EVIDENCE_NAME,
        "Roadmap file: " + ROADMAP_NAME,
        "Roadmap status: Landed",
        "Roadmap path: docs/implementation-plans/"
        "2026-08-20-pinned-dispatch-fallback/plan.md",
        "",
        "## Polytoken runtime/workflow model",
        "Facets compose prompts via transclude; subagents return via "
        "exit_tool.",
        "",
        "## Existing ed3d/Copilot workflow model",
        "Copilot CLI uses agents, skills, and hooks.",
        "",
        "## Capability-by-capability equivalence matrix",
        "| Capability | Polytoken mechanism | Copilot CLI equivalent | "
        "Verdict | Semantic IDs |",
        "|---|---|---|---|---|",
    ]
    for cap in parser.CAPABILITY_IDS:
        sids = ", ".join(CAP_TO_SEM[cap])
        lines.append("| %s | mechanism-%s | equivalent-%s | %s | %s |"
                     % (cap, cap, cap, VERDICTS[cap], sids))
    lines += [
        "",
        "## Quality-impact/cost ranking",
        "1. Highest impact: RESEARCH_DECOMPOSITION.",
        "",
        "## Case study: research failure and missing controls",
        "Missing evidence controls let an unresolved case study go "
        "undetected.",
    ]
    for case in evidence["case_study_citations"]:
        lines.append("- %s: %s (%s)"
                     % (case["label"], case["uri"], case["status"]))
    lines += [
        "",
        "## Recommended MVP ports, deferred work, and explicit non-goals",
        "- **RECOMMENDATION:** Port the plan facet control-plane handoff.",
        "  - benefit: restores plan-then-execute gating",
        "  - touched_files: plugins/ed3d-plan-and-execute",
        "  - mechanism: custom agent + slash command",
        "  - testability: hermetic offline test",
        "  - success_measurement: handoff passes validator",
        "- **RECOMMENDATION:** Re-express subagents as Copilot agents.",
        "  - benefit: preserves evidence contracts",
        "  - touched_files: plugins/ed3d-basic-agents",
        "  - mechanism: agent frontmatter grants",
        "  - testability: fixture-based replay",
        "  - success_measurement: replay replays cleanly",
        "",
        "## Compatibility and version risks",
        "Hook schema coupled to installed CLI version.",
        "",
        "## Source index",
    ]
    for root in roots:
        label = "root-" + root.rstrip("/").split("/")[-1].replace(".", "-")
        lines.append("- %s: %s" % (label, root))
    for record in evidence["local_citations"]:
        label = "local-" + record["path"].replace("/", "-").replace(".", "-")
        lines.append("- %s: %s" % (label, record["path"]))
    lines.append("- hooks-ref: " + URL_REF)
    return "\n".join(lines) + "\n"


def build_fixture(tmpdir, content=None, audit_mutator=None,
                  roadmap_text=None, evidence_mutator=None):
    """Write a full three-artifact fixture; return the paths + objects."""
    content = dict(DEFAULT_CONTENT) if content is None else dict(content)
    evidence = build_evidence(content)
    if evidence_mutator is not None:
        evidence_mutator(evidence)
    audit = build_audit(evidence)
    if audit_mutator is not None:
        audit = audit_mutator(audit)
    if roadmap_text is None:
        roadmap_text = VALID_ROADMAP_TEXT

    audit_path = os.path.join(tmpdir, AUDIT_NAME)
    evidence_path = os.path.join(tmpdir, EVIDENCE_NAME)
    roadmap_path = os.path.join(tmpdir, ROADMAP_NAME)
    with open(audit_path, "w", encoding="utf-8") as handle:
        handle.write(audit)
    with open(evidence_path, "w", encoding="utf-8") as handle:
        json.dump(evidence, handle, indent=2, sort_keys=True)
    with open(roadmap_path, "w", encoding="utf-8") as handle:
        handle.write(roadmap_text)

    catmap_path = os.path.join(tmpdir, "catmap.json")
    with open(catmap_path, "w", encoding="utf-8") as handle:
        json.dump({r["uri"]: r.get("content", "") for r in
                   evidence["resources"]}, handle)
    fakecat_path = os.path.join(tmpdir, "fakecat.py")
    with open(fakecat_path, "w", encoding="utf-8") as handle:
        handle.write(FAKE_CAT)
    log_path = os.path.join(tmpdir, "cat.log")
    return {
        "audit": audit_path,
        "evidence": evidence_path,
        "roadmap": roadmap_path,
        "fakecat": fakecat_path,
        "catmap": catmap_path,
        "log": log_path,
        "evidence_obj": evidence,
        "audit_text": audit,
    }


def cat_command(fixture):
    """Test-only PORTABILITY_VFS_CAT_COMMAND pointing at the fake cat."""
    return "%s %s %s %s" % (sys.executable, fixture["fakecat"],
                            fixture["catmap"], fixture["log"])


def run_validator(fixture):
    return subprocess.run(
        [sys.executable, os.path.join(HERE, "validate_portability_audit.py"),
         fixture["audit"], fixture["evidence"], fixture["roadmap"]],
        capture_output=True, text=True, check=False)


def run_replay(fixture, with_cat=True):
    env = os.environ.copy()
    if with_cat:
        env[replay.CAT_COMMAND_ENV] = cat_command(fixture)
    return subprocess.run(
        [sys.executable, os.path.join(HERE, "replay_portability_evidence.py"),
         fixture["evidence"]],
        capture_output=True, text=True, check=False, env=env)


def run_parser_scan(path):
    return subprocess.run(
        [sys.executable, os.path.join(HERE, "portability_evidence_parser.py"),
         "--scan", path],
        capture_output=True, text=True, check=False)


def write_temp(text, suffix):
    with tempfile.NamedTemporaryFile("w", suffix=suffix, delete=False) as h:
        h.write(text)
        return h.name


def assert_fails_validator(fixture, needle=None):
    result = run_validator(fixture)
    assert result.returncode != 0, \
        "validator unexpectedly passed:\n%s%s" % (result.stdout, result.stderr)
    if needle:
        assert needle in result.stdout + result.stderr, \
            "expected %r in:\n%s%s" % (needle, result.stdout, result.stderr)


def assert_fails_replay(fixture, needle=None, with_cat=True):
    result = run_replay(fixture, with_cat=with_cat)
    assert result.returncode != 0, \
        "replay unexpectedly passed:\n%s%s" % (result.stdout, result.stderr)
    if needle:
        assert needle in result.stdout + result.stderr, \
            "expected %r in:\n%s%s" % (needle, result.stdout, result.stderr)


# ---------------------------------------------------------------------------
# Shared parser: scanning, normalization, ordering, warnings, closure
# ---------------------------------------------------------------------------

def test_parser_evidence_keys_are_exactly_eight():
    assert parser.EVIDENCE_KEYS == (
        "roots", "resources", "unresolved_references", "semantic_sources",
        "local_citations", "workflow_stages", "case_study_citations",
        "manual_review",
    )


def test_parser_roots_are_the_six_facet_subagent_uris():
    assert parser.EXPECTED_ROOTS == (
        "polytoken://facets/plan.md",
        "polytoken://facets/execute.md",
        "polytoken://facets/orchestrate.md",
        "polytoken://subagents/researcher.md",
        "polytoken://subagents/plan-reviewer.md",
        "polytoken://subagents/general-purpose.md",
    )


def test_parser_capability_ids_exact():
    assert parser.CAPABILITY_IDS == (
        "RESEARCH_DECOMPOSITION", "SUBAGENT_HANDOFF", "EVIDENCE_CONTRACTS",
        "FACET_SEPARATION", "MODEL_TOOL_SKILL_SCOPING", "PLAN_REVIEW_GATE",
        "ADVERSARIAL_REVIEW", "MECHANICAL_ENFORCEMENT",
        "CONTEXT_RESUME_STATE", "COMPLETION_SUMMARY",
        "TEMPLATING_COMPOSABILITY", "OBSERVABILITY",
    )


def test_parser_semantic_ids_exact():
    assert parser.SEMANTIC_IDS == (
        "SUBAGENT_INVOCATION", "SUBAGENT_ISOLATION", "SUBAGENT_RESULT_RETURN",
        "SUBAGENT_TOOL_INHERITANCE", "SUBAGENT_MODEL_CONFIG",
        "SUBAGENT_SKILL_ACCESS", "FACET_PROMPT_COMPOSITION",
        "FACET_TOOL_FILTERING", "FACET_SKILL_FILTERING",
        "FACET_MODEL_SELECTION", "FACET_TRANSITIONS",
        "FACET_COMPACTION_HINT", "FACET_PERMISSION_HINT", "SKILL_LOADING",
        "HOOK_TIMING", "HOOK_ENFORCEMENT", "TEMPLATING_RUNTIME",
        "TRANSCLUDE_SEMANTICS", "VFS_INSPECTION", "SESSION_CONTINUITY",
        "SESSION_CLEAR", "SESSION_COMPACTION", "WEB_SEARCH",
    )


def test_parser_manual_review_ids_exact():
    assert parser.MANUAL_REVIEW_IDS == ("WF-1", "WF-2", "CASE-1",
                                        "SRC-1", "SRC-2")


def test_parser_scan_transclude_quoted_uri_and_literal_token():
    text = ("{{ transclude(\"polytoken://system_prompts/facet.md\") }}\n"
            "polytoken://vfs/AGENTS.md\n")
    scan = parser.scan_content(text)
    assert scan["references"] == [
        {"target": "polytoken://system_prompts/facet.md", "line": 1,
         "source": "transclude"},
        {"target": "polytoken://vfs/AGENTS.md", "line": 2,
         "source": "literal"},
    ]


def test_parser_transclude_single_and_double_quotes():
    text = ("transclude('polytoken://vfs/a.md')\n"
            "transclude(\"polytoken://vfs/b.md\")\n")
    scan = parser.scan_content(text)
    sources = [r["source"] for r in scan["references"]]
    assert sources == ["transclude", "transclude"]


def test_parser_normalization_and_lexical_order():
    scan = parser.scan_content(
        "polytoken://VFS/README.md\n"
        "transclude(\"polytoken://vfs/b.md\")\n"
        "transclude('polytoken://vfs/a.md')\n"
        "polytoken://vfs/AGENTS.md\n")
    assert [r["target"] for r in scan["references"]] == [
        "polytoken://vfs/AGENTS.md",
        "polytoken://vfs/README.md",
        "polytoken://vfs/a.md",
        "polytoken://vfs/b.md",
    ]


def test_parser_non_uri_transclude_is_not_a_dependency():
    scan = parser.scan_content("transclude('plugins/x/SKILL.md')\n")
    assert scan["references"] == []


def _scan_warnings(text):
    warnings = []
    parser.scan_content(text, lambda msg: warnings.append(msg))
    return warnings


def test_parser_warns_unterminated_transclude():
    warnings = _scan_warnings("transclude(\"unterminated\n")
    assert any("unterminated transclude" in w for w in warnings)


def test_parser_warns_unquoted_transclude():
    warnings = _scan_warnings("transclude(unquoted)\n")
    assert any("malformed transclude call" in w for w in warnings)


def test_parser_warns_empty_transclude_target():
    warnings = _scan_warnings("transclude('')\n")
    assert any("empty transclude target" in w for w in warnings)


def test_parser_warns_malformed_polytoken_uri():
    warnings = _scan_warnings("polytoken://vfs\n")
    assert any("missing authority/path" in w for w in warnings)


def test_parser_unsupported_scheme_warns_and_is_not_a_dependency():
    # Unsupported schemes warn on stderr only and do not become deps; a
    # polytoken:// token with any authority is a dependency.
    scan = parser.scan_content("ftp://x\n"
                               "transclude(\"gopher://y\")\n"
                               "polytoken://system_prompts/facet.md\n"
                               "polytoken://vfs/AGENTS.md\n")
    assert [r["target"] for r in scan["references"]] == [
        "polytoken://system_prompts/facet.md",
        "polytoken://vfs/AGENTS.md",
    ]


def test_parser_warns_unsupported_uri_scheme():
    warnings = _scan_warnings("ftp://x\n")
    assert any("unsupported uri scheme" in w for w in warnings)


def test_parser_transclude_uri_not_double_counted():
    # The same URI inside a transclude must not also be captured as a
    # literal token.
    text = ("{{ transclude(\"polytoken://system_prompts/facet.md\") }}\n"
            "polytoken://vfs/AGENTS.md\n")
    scan = parser.scan_content(text)
    assert len(scan["references"]) == 2


def test_parser_closure_helpers():
    resources = [
        {"uri": "polytoken://vfs/a",
         "discovered_references": [{"target": "polytoken://vfs/b",
                                    "line": 1, "source": "transclude"}]},
        {"uri": "polytoken://vfs/b", "discovered_references": []},
    ]
    closure, unresolved = parser.recompute_evidence(
        ["polytoken://vfs/a"], resources)
    assert closure == ["polytoken://vfs/a", "polytoken://vfs/b"]
    assert unresolved == []


def test_parser_cli_subprocess_clean():
    path = write_temp(
        "transclude(\"polytoken://system_prompts/facet.md\")\n"
        "polytoken://vfs/AGENTS.md\n", ".txt")
    try:
        result = run_parser_scan(path)
        assert result.returncode == 0, result.stdout + result.stderr
        assert "dependency(s) scanned cleanly" in result.stdout
        assert "warning:" not in result.stderr
    finally:
        os.unlink(path)


def test_parser_cli_subprocess_unsupported_scheme_warns():
    path = write_temp("ftp://x\n", ".txt")
    try:
        result = run_parser_scan(path)
        assert result.returncode == 1
        assert "warning:" in result.stderr
        assert "unsupported uri scheme" in result.stderr
        assert "dependency(s) scanned cleanly" not in result.stdout
    finally:
        os.unlink(path)


# ---------------------------------------------------------------------------
# Validator: positive fixture + every negative category
# ---------------------------------------------------------------------------

def test_validator_accepts_complete_fixture():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        result = run_validator(fixture)
        assert result.returncode == 0, result.stdout + result.stderr
        assert "OK: portability audit is valid" in result.stdout


def test_validator_no_warning_fields_on_valid_fixture():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        result = run_validator(fixture)
        assert result.returncode == 0
        assert result.stderr == "", "expected no stderr, got %r" % result.stderr


def test_validator_rejects_missing_heading():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "## Executive answer\n", ""))
        assert_fails_validator(fixture, "headings must be exactly")


def test_validator_rejects_reordered_headings():
    def mutate(a):
        return a.replace("## Quality-impact/cost ranking\n",
                         "## XSwap\n", 1) \
                .replace("## Compatibility and version risks\n",
                         "## Quality-impact/cost ranking\n", 1) \
                .replace("## XSwap\n",
                         "## Compatibility and version risks\n", 1)
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, audit_mutator=mutate)
        assert_fails_validator(fixture, "headings must be exactly")


def test_validator_rejects_extra_heading():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "## Executive answer\n",
                "## Appendix\n## Executive answer\n"))
        assert_fails_validator(fixture, "headings must be exactly")


def test_validator_rejects_wrong_capability_id():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "| RESEARCH_DECOMPOSITION |", "| BOGUS_CAP |", 1))
        assert_fails_validator(fixture, "unknown capability id")


def test_validator_rejects_matrix_missing_row():
    def mutate(a):
        return a.replace("| OBSERVABILITY | mechanism-OBSERVABILITY",
                         "| DROPPED | mechanism-DROPPED") \
                .replace("| DROPPED | mechanism-DROPPED | equivalent-OBSERVABILITY | partial | VFS_INSPECTION |\n", "")
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, audit_mutator=mutate)
        assert_fails_validator(fixture, "exactly the 12")


def test_validator_rejects_matrix_bad_verdict():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "| OBSERVABILITY | mechanism-OBSERVABILITY | "
                "equivalent-OBSERVABILITY | partial | VFS_INSPECTION |",
                "| OBSERVABILITY | mechanism-OBSERVABILITY | "
                "equivalent-OBSERVABILITY | ship | VFS_INSPECTION |"))
        assert_fails_validator(fixture, "verdict")


def test_validator_rejects_unknown_semantic_id():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "| OBSERVABILITY | mechanism-OBSERVABILITY | "
                "equivalent-OBSERVABILITY | partial | VFS_INSPECTION |",
                "| OBSERVABILITY | mechanism-OBSERVABILITY | "
                "equivalent-OBSERVABILITY | partial | BOGUS_SEM |"))
        assert_fails_validator(fixture, "unknown semantic id")


def test_validator_rejects_semantic_union_incomplete():
    def mutate(a):
        return a.replace("| RESEARCH_DECOMPOSITION |", "| RES_DROP |") \
                .replace("| RES_DROP | mechanism-RESEARCH_DECOMPOSITION | "
                         "equivalent-RESEARCH_DECOMPOSITION | portable | "
                         "WEB_SEARCH |\n", "")
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, audit_mutator=mutate)
        assert_fails_validator(fixture, "union must be exactly")


def test_validator_rejects_four_recommendations():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "## Recommended MVP ports, deferred work, and explicit "
                "non-goals\n",
                "## Recommended MVP ports, deferred work, and explicit "
                "non-goals\n"
                "- **RECOMMENDATION:** Extra one.\n"
                "  - benefit: x\n  - touched_files: y\n"
                "  - mechanism: z\n  - testability: t\n"
                "  - success_measurement: s\n"
                "- **RECOMMENDATION:** Extra two.\n"
                "  - benefit: x\n  - touched_files: y\n"
                "  - mechanism: z\n  - testability: t\n"
                "  - success_measurement: s\n"))
        assert_fails_validator(fixture, "too many RECOMMENDATION")


def test_validator_rejects_recommendation_missing_field():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "  - success_measurement: handoff passes validator\n",
                "", 1))
        assert_fails_validator(fixture, "missing field")


def test_validator_rejects_missing_required_root_citation():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "- root-plan-md: polytoken://facets/plan.md\n", ""))
        assert_fails_validator(fixture, "required citation for root")


def test_validator_rejects_invalid_citation_url():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "- hooks-ref: " + URL_REF, "- hooks-ref: https://"))
        assert_fails_validator(fixture, "not syntactically valid")


def test_validator_rejects_citation_path_missing():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "- local-AGENTS-md: AGENTS.md",
                "- local-AGENTS-md: no/such/file.md"))
        assert_fails_validator(fixture, "cited path does not exist")


def test_validator_rejects_extra_evidence_key():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, evidence_mutator=lambda e: e.__setitem__("extra", True))
        assert_fails_validator(fixture, "top-level keys must be exactly")


def test_validator_rejects_unknown_evidence_key():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, evidence_mutator=lambda e: e.__setitem__(
                "bogus_array", []))
        assert_fails_validator(fixture, "top-level keys must be exactly")


def test_validator_rejects_missing_evidence_key():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, evidence_mutator=lambda e: e.pop("manual_review"))
        assert_fails_validator(fixture, "top-level keys must be exactly")


def test_validator_rejects_roots_not_exactly_six():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, evidence_mutator=lambda e: e.__setitem__(
                "roots", list(parser.EXPECTED_ROOTS) +
                ["polytoken://facets/extra.md"]))
        assert_fails_validator(fixture, "exactly the six expected roots")


def test_validator_rejects_resource_missing_required_field():
    def mutate(e):
        del e["resources"][0]["content"]
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "missing key")


def test_validator_rejects_root_parent_uri_not_null():
    def mutate(e):
        e["resources"][0]["parent_uri"] = "polytoken://facets/other.md"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "parent_uri null")


def test_validator_rejects_non_root_parent_null():
    def mutate(e):
        e["resources"].append({
            "uri": "polytoken://system_prompts/facet.md",
            "parent_uri": None,
            "retrieval_status": "retrieved",
            "content": "x",
            "content_sha256": "0" * 64,
            "discovered_references": [],
        })
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "non-null parent_uri")


def test_validator_rejects_bad_content_sha256():
    def mutate(e):
        e["resources"][0]["content_sha256"] = "zz"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "content_sha256")


def test_validator_rejects_references_mismatch():
    def mutate(e):
        first = e["resources"][0]["uri"]
        refs = e["resources"][0]["discovered_references"]
        e["resources"][0]["discovered_references"] = refs[:1] if refs else []
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "do not match a re-scan")


def test_validator_rejects_unresolved_mismatch():
    def mutate(e):
        e["unresolved_references"].append("polytoken://vfs/bogus.md")
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "unresolved")


def test_validator_rejects_semantic_ids_wrong_set():
    def mutate(e):
        e["semantic_sources"] = e["semantic_sources"][1:]
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "exactly the 23 semantic")


def test_validator_rejects_semantic_unknown_capability():
    def mutate(e):
        e["semantic_sources"][0]["capability"] = "BOGUS_CAP"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "unknown capability")


def test_validator_rejects_unresolved_semantic_claim_on_retrieved_uri():
    """A claim's evidence class and URI mapping must agree."""
    def mutate(e):
        record = e["semantic_sources"][0]
        record["evidence_class"] = "unresolved"
        record["url"] = "polytoken://facets/plan.md"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "unresolved claim must reference")


def test_validator_rejects_workflow_stage_bad_source():
    def mutate(e):
        e["workflow_stages"][0]["source_uri"] = "polytoken://facets/nope.md"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "source_uri")


def test_validator_rejects_workflow_stage_union_incomplete():
    def mutate(e):
        e["workflow_stages"][0]["semantic_ids"] = []
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "union must cover exactly")


def test_validator_rejects_case_study_all_observed():
    def mutate(e):
        for c in e["case_study_citations"]:
            c["status"] = "observed"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "at least one citation marked "
                                        "unresolved")


def test_validator_rejects_case_study_bad_status():
    def mutate(e):
        e["case_study_citations"][0]["status"] = "bogus"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "status")


def test_validator_rejects_manual_review_wrong_id():
    def mutate(e):
        e["manual_review"][0]["id"] = "MR-99"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "manual_review ids must be exactly")


def test_validator_rejects_manual_review_not_pass():
    def mutate(e):
        e["manual_review"][2]["status"] = "fail"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "must be 'pass'")


def test_validator_rejects_local_citation_missing():
    def mutate(e):
        e["local_citations"].append({"path": "no/such/dir/file.md"})
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "local citation path does not exist")


def test_validator_rejects_roadmap_status_mismatch():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, roadmap_text="Deferred: nothing.\n")
        assert_fails_validator(fixture, "roadmap status keyword")


def test_validator_rejects_roadmap_path_missing():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(
            tmp, audit_mutator=lambda a: a.replace(
                "Roadmap path: docs/implementation-plans/"
                "2026-08-20-pinned-dispatch-fallback/plan.md",
                "Roadmap path: no/such/plan.md"))
        assert_fails_validator(fixture, "roadmap path does not exist")


def test_validator_rejects_missing_evidence_file():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        missing = os.path.join(tmp, "NOPE.json")
        result = subprocess.run(
            [sys.executable,
             os.path.join(HERE, "validate_portability_audit.py"),
             fixture["audit"], missing, fixture["roadmap"]],
            capture_output=True, text=True, check=False)
        assert result.returncode != 0
        assert "does not exist" in result.stdout


# ---------------------------------------------------------------------------
# Replay: positive + negatives
# ---------------------------------------------------------------------------

def test_replay_accepts_complete_fixture():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        result = run_replay(fixture)
        assert result.returncode == 0, result.stdout + result.stderr
        assert "OK: recorded evidence replays cleanly" in result.stdout


def test_replay_no_warning_fields_on_valid_fixture():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        result = run_replay(fixture)
        assert result.returncode == 0
        assert result.stderr == "", "expected no stderr, got %r" % result.stderr


def test_replay_invokes_vfs_cat_in_deterministic_uri_order():
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        result = run_replay(fixture)
        assert result.returncode == 0, result.stdout + result.stderr
        with open(fixture["log"], encoding="utf-8") as handle:
            called = [line for line in handle.read().splitlines() if line]
        expected = sorted(r["uri"] for r in
                          fixture["evidence_obj"]["resources"])
        assert called == expected, "cat order not deterministic: %r" % called


def test_replay_uses_test_only_cat_command():
    # Without PORTABILITY_VFS_CAT_COMMAND the default command is the exact
    # `polytoken vfs cat <uri>`; with the env var set the fake is consulted.
    assert replay.vfs_cat_command("polytoken://facets/plan.md") == [
        "polytoken", "vfs", "cat", "polytoken://facets/plan.md"]
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp)
        os.environ[replay.CAT_COMMAND_ENV] = cat_command(fixture)
        try:
            assert replay.vfs_cat_command("u")[0] == sys.executable
        finally:
            del os.environ[replay.CAT_COMMAND_ENV]


def test_validator_rejects_content_mutation_with_stale_hash():
    def mutate(e):
        e["resources"][0]["content"] += "tampered"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_validator(fixture, "content_sha256 mismatch")


def test_replay_rejects_wrong_roots():
    def mutate(e):
        e["roots"][0] = "polytoken://fabricated/root.md"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_replay(fixture, "exactly the six expected roots")


def test_replay_rejects_fabricated_semantic_metadata():
    def mutate(e):
        e["semantic_sources"][0]["claim_id"] = "FABRICATED"
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_replay(fixture, "exactly the 23 semantic")


def test_replay_rejects_sha256_mismatch():
    def mutate(e):
        e["resources"][0]["content_sha256"] = "0" * 64
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_replay(fixture, "sha256 mismatch")


def test_replay_rejects_unresolved_mismatch():
    def mutate(e):
        e["unresolved_references"].append("polytoken://vfs/bogus.md")
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_replay(fixture, "unresolved")


def test_replay_rejects_bad_url_metadata():
    def mutate(e):
        e["case_study_citations"].append(
            {"label": "bad", "uri": "http://", "status": "observed"})
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, evidence_mutator=mutate)
        assert_fails_replay(fixture, "not syntactically valid")


def test_replay_rejects_missing_evidence_file():
    with tempfile.TemporaryDirectory() as tmp:
        result = subprocess.run(
            [sys.executable,
             os.path.join(HERE, "replay_portability_evidence.py"),
             os.path.join(tmp, "NOPE.json")],
            capture_output=True, text=True, check=False)
        assert result.returncode != 0
        assert "does not exist" in result.stdout


# ---------------------------------------------------------------------------
# Parser-warning stdout/stderr parity between validator and replay
# ---------------------------------------------------------------------------

def test_parser_warning_parity_validator_vs_replay():
    # Malformed token inside a root's content: the shared parser emits the
    # same deterministic warning through both CLIs, and the malformed token
    # is a warning, not a dependency, so both pass.
    bad_content = dict(DEFAULT_CONTENT)
    bad_content["polytoken://facets/plan.md"] = (
        "{{ transclude(\"polytoken://system_prompts/facet.md\") }}\n"
        "{{ transclude(\"unterminated\n"
        "{{ transclude(\"polytoken://resources/plan_spec_default.md\") }}\n"
    )
    with tempfile.TemporaryDirectory() as tmp:
        fixture = build_fixture(tmp, content=bad_content)
        v_result = run_validator(fixture)
        r_result = run_replay(fixture)
        assert "parser warning:" in v_result.stderr
        assert v_result.stderr == r_result.stderr, (
            "validator and replay stderr differ:\nVALIDATOR=%r\nREPLAY=%r"
            % (v_result.stderr, r_result.stderr))
        assert v_result.returncode == 0, v_result.stdout
        assert r_result.returncode == 0, r_result.stdout


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

TESTS = [name for name in globals() if name.startswith("test_")]


def main():
    failures = []
    for name in sorted(TESTS):
        try:
            globals()[name]()
            print("PASS %s" % name)
        except Exception as exc:
            failures.append((name, exc))
            print("FAIL %s: %s" % (name, exc))
    print("%d/%d portability audit tests passed"
          % (len(TESTS) - len(failures), len(TESTS)))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
